[master]
slurmmaster ansible_host=192.168.18.176 ansible_user=user ansible_become_pass=password

[database]
slurmdata ansible_host=192.168.18.167 ansible_user=user ansible_become_pass=password

[compute]
worker1 ansible_host=192.168.18.175 ansible_user=user ansible_become_pass=password node_feature=standperf
worker2 ansible_host=192.168.18.177 ansible_user=user ansible_become_pass=password node_feature=highperf

[slurm_cluster:children]
master
database
compute

[all:vars]
ansible_become=true
